"""PlatformIO pre-build script: optional development settings from .env.

Release builds carry no credentials; the device asks for them through its own
setup portal. For development it is handy if a freshly flashed device is ready
straight away, so this script turns these settings into include/secrets.h:

  WIFI_SSID, WIFI_PASS   WiFi network
  CALENDAR_URL           Apps Script web app URL, including ?token=...
  WEATHER_LAT, WEATHER_LON

They are read from .env in the project root (copy .env.example), and
environment variables of the same name override it. Both .env and the
generated header are gitignored. With no settings, the header is removed and
the build proceeds without, exactly like CI.
"""
import os
from pathlib import Path

Import("env")  # noqa: F821 - provided by PlatformIO/SCons

project_dir = Path(env["PROJECT_DIR"])  # noqa: F821
dotenv = project_dir / ".env"
header = project_dir / "include" / "secrets.h"

STRINGS = ["WIFI_SSID", "WIFI_PASS", "CALENDAR_URL"]
NUMBERS = ["WEATHER_LAT", "WEATHER_LON"]
MARKER = "// Generated by tools/gen_secrets.py"


def read_dotenv(path: Path) -> dict:
    """KEY=VALUE lines; # starts a comment only at the start of a line, so
    passwords may contain it. Values may be wrapped in single or double quotes."""
    values = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip().removeprefix("export ").strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
            value = value[1:-1]
        values[key] = value
    return values


def c_string_literal(value: str) -> str:
    """Escape a Python string as a C string literal body (UTF-8 kept as-is)."""
    out = []
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "?":
            out.append("\\?")   # no accidental trigraphs
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append("\\x%02x" % ord(ch))
        else:
            out.append(ch)
    return "".join(out)


settings = read_dotenv(dotenv)
for name in STRINGS + NUMBERS:
    if os.environ.get(name):
        settings[name] = os.environ[name]

lines = []
for name in STRINGS:
    if settings.get(name):
        lines.append(f'#define {name} "{c_string_literal(settings[name])}"\n')
for name in NUMBERS:
    if settings.get(name):
        lines.append(f"#define {name} {float(settings[name])}f\n")

if lines:
    content = (
        f"{MARKER} from .env / environment variables.\n"
        "// Gitignored - do not edit or commit; change .env instead.\n"
        "#pragma once\n" + "".join(lines)
    )
    header.parent.mkdir(parents=True, exist_ok=True)
    if not header.exists() or header.read_text(encoding="utf-8") != content:
        header.write_text(content, encoding="utf-8")
        print(f"gen_secrets: wrote {header.relative_to(project_dir)} ({len(lines)} settings)")
    else:
        print("gen_secrets: include/secrets.h is up to date")
else:
    if header.exists():
        header.unlink()
        print("gen_secrets: no settings, removed include/secrets.h")
    print("gen_secrets: no development settings; device will use its setup portal")
